# Xcode project configuration. Managed by https://github.com/yonaskolb/XcodeGen
# Xcode is only used to build the release App Bundle. Debug builds only use Swift Package Manager

name: SceneMux

packages:
  WinMuxPackage:
    path: .

configs:
  Debug: debug
  Release: release

targets:
  SceneMux:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    info:
      path: resources/SceneMux-Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSUIElement: true
        SUEnableAutomaticChecks: false
    sources:
      - "Sources/SceneMuxApp"
      - "resources"
    dependencies:
      - package: WinMuxPackage
        product: AppBundle
      - package: WinMuxPackage
        product: SparkleSupport
    # https://developer.apple.com/documentation/xcode/build-settings-reference
    settings:
      base:
        SWIFT_VERSION: 6.2 # Swift Language Version
        MARKETING_VERSION: ${XCODEGEN_SCENEMUX_VERSION}
        CURRENT_PROJECT_VERSION: ${XCODEGEN_SCENEMUX_VERSION}
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: ${XCODEGEN_SCENEMUX_CODE_SIGN_IDENTITY}
        DEVELOPMENT_TEAM: ${XCODEGEN_SCENEMUX_DEVELOPMENT_TEAM}
      configs:
        Debug:
          PRODUCT_NAME: SceneMux-Debug
          PRODUCT_BUNDLE_IDENTIFIER: com.chisanan232.scenemux.debug
        Release:
          PRODUCT_NAME: SceneMux
          PRODUCT_BUNDLE_IDENTIFIER: com.chisanan232.scenemux
          SWIFT_TREAT_WARNINGS_AS_ERRORS: YES
          GCC_TREAT_WARNINGS_AS_ERRORS: YES
    entitlements:
      path: resources/SceneMux.entitlements
      properties:
        # Accessibility API doesn't work in sandboxed apps
        com.apple.security.app-sandbox: false
